spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: b10f5144f63bda
    password: c970226f295856
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth:
          starttls:
            enable: true
  datasource:
    driverclassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paymentdb
    username: dbeaver
    password: dbeaver
  jpa:
    properties:
      hibernate:
        show sql: true
        format sql: true
  cache:
    type: redis
  redis:
      host: localhost
      port: 6379
jwt:
  secret: secret
