spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: b10f5144f63bda
    password: c970226f295856
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth:
          starttls:
            enable: true
  datasource:
    driverclassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://kavfu5f7pido12mr.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:33606/duc03sjtnj507i9t
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        show sql: true
        format sql: true
  cache:
    type: redis
  redis:
    host: redis-15223.c89.us-east-1-3.ec2.cloud.redislabs.com
    port: 15223
    password: ${REDIS_PASSWORD}
jwt:
  secret: secret
